# Generated by Django 3.0.5 on 2020-12-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('choose_one', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.CharField(max_length=500)),
                ('is_choice_limit', models.BooleanField(default=False)),
                ('choice_limit', models.IntegerField(default=2)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.SimpleQuiz')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.SimpleQuestion')),
            ],
        ),
    ]
